In [1]:
import numpy as np
import numpy.linalg as LA
import matplotlib.pyplot as plt
from quantecon import LQ

In [2]:
a0 = 10.

a1 = 1.

β = 0.99

ρ0 = 0. 

ρ1 = 1.2

ρ2 = -0.4

d = 0.1

σ = 0.1

In [3]:
R = np.matrix(
    [[-a1, a0/2, -1/2, 0.],
     [a0/2, 0., 0., 0.],
     [-1/2, 0., 0., 0.],
     [0., 0., 0., 0.]])

A = np.matrix(
    [[1., 0., 0., 0.],
     [0., 1., 0., 0.],
     [0., ρ0, ρ1, ρ2],
     [0., 0., 1., 0.]])

B = np.matrix([[1.], [0.], [0.], [0.]])

C = np.matrix([[0.], [0.], [σ], [0.]])

Q = np.matrix(d)

In [4]:
lq = LQ(Q, R, A, B, C, beta = β, T = None, Rf = None)

In [5]:
P, F, h = lq.stationary_values()
print("P =", P)
print("F = ", F)

P = [[-8.87151148e-01  4.43575574e+00 -4.31362962e-01 -2.19483750e-02]
 [ 4.43575574e+00  2.47782122e+03 -1.00956847e+01  4.96173168e+00]
 [-4.31362962e-01 -1.00956847e+01  9.02102747e-01 -3.91063632e-01]
 [-2.19483750e-02  4.96173168e+00 -3.91063632e-01  1.80385231e-01]]
F =  [[ 1.12848852 -5.64244261  0.68637038 -0.21948375]]


In [6]:
def verify1(A, B, Q, P, F):
    
    n, n = np.shape(P)
    I = np.identity(n)
    lhs = LA.inv(I + B @ LA.inv(Q) @ B.T @ P) @ A 
    rhs = A - B @ F
    #print(lhs, rhs)
    
    if (lhs == rhs).all:
        print('True')
    else:
        print ('False')

In [7]:
verify1(A, B, Q, P, F)

True


In [8]:
n, n = np.shape(P)
I = np.identity(n)
lhs = LA.inv(I + B @ LA.inv(Q) @ B.T @ P) @ A 
rhs = A - B @ F
    
lhs - rhs
print("lhs= ", lhs)
print("rhs= ", rhs)
print("rhs-lhs", rhs-lhs)

lhs=  [[-0.1270404   5.63520202 -0.6854896   0.2192021 ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.2        -0.4       ]
 [ 0.          0.          1.          0.        ]]
rhs=  [[-0.12848852  5.64244261 -0.68637038  0.21948375]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.2        -0.4       ]
 [ 0.          0.          1.          0.        ]]
rhs-lhs [[-0.00144812  0.00724059 -0.00088078  0.00028165]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [9]:
def verify2(A, B, Q, P, F):
    
   
    rhs = (R + F.T @ Q @ F) + (A - B @ F).T @ P @ (A - B @ F)
    lhs = P
    
    #print(lhs, rhs)
    if (lhs == rhs).all:
        print('True')
    else:
        print ('False')

In [10]:
rhs = (R + F.T @ Q @ F) + β*(A - B @ F).T @ P @ (A - B @ F)
rhs - P

matrix([[-3.33066907e-16,  0.00000000e+00,  5.55111512e-17,
         -3.46944695e-18],
        [ 0.00000000e+00,  0.00000000e+00, -3.55271368e-15,
          0.00000000e+00],
        [ 5.55111512e-17, -1.77635684e-15, -7.77156117e-16,
          1.72084569e-15],
        [-3.46944695e-18,  0.00000000e+00, -4.99600361e-16,
         -4.16333634e-16]])

In [11]:
verify2(A, B, Q, P, F)

True


In [12]:
def verify3(A, B, Q, P, F):
    
   
    rhs = R + A.T @ P @ A
    lhs = P
    
    #print(lhs, rhs)
    if (lhs == rhs).all:
        print('True')
    else:
        print ('False')

In [16]:
rhs1 = (R ) + β*A.T @ P @ (A - B@F)
P - rhs1

print ("it works like a charm: notice the formula")
print("P - rhs1 = ", P - rhs)

it works like a charm: notice the formula
P - rhs1 =  [[ 3.33066907e-16  0.00000000e+00 -5.55111512e-17  3.46944695e-18]
 [ 0.00000000e+00  0.00000000e+00  3.55271368e-15  0.00000000e+00]
 [-5.55111512e-17  1.77635684e-15  7.77156117e-16 -1.72084569e-15]
 [ 3.46944695e-18  0.00000000e+00  4.99600361e-16  4.16333634e-16]]


In [14]:
verify3(A, B, Q, P, F)

True
